language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install khleepkg03
  - pip install coveralls

script:
  - nosetests --with-coverage --cover-package=khleepkg03

after_success:
  - coveralls

branches:
  only:
  - master