language: python
python:
  - "3"
  - "3.1"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install -r requirement.txt
  - pip install khleepkg03

script:
  - python3 ./test/module.py
  - python3 ./test/calc/add.py
  - python3 ./test/calc/sub.py
  - python3 ./test/calc/mul.py
  - python3 ./test/calc/div.py

branches:
  only:
  - master