language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install khleepkg03
  - pip install coveralls

script:
  - coverage run --source=khleepkg03 setup.py test

after_success:
  - coveralls

branches:
  only:
  - master
